### ISSUE TITLE
Depreciated vs deprecated

### ISSUE THREAD

**Issue by theorician** [Motion-Project/Motion-Project.github.io#5]
You use the word 'depreciated' a lot in the Motion docs. You probably mean 'deprecated' instead. Examples abound, e.g.: https://github.com/Motion-Project/Motion-Project.github.io/blob/master/4.3.2/motion_config.html#L182

**Comment by Mr-Dave** [comment]
Sigh...Yet another example of why I should not have done my math homework during English class.  Thank you.  I'll create a PR to fix this.
