### ISSUE TITLE
unable to download the buildplus.sh script. An invalid URL found while trying to build a deb package. 

### ISSUE THREAD

**Issue by abdullahfarwees** [Motion-Project/Motion-Project.github.io#9]
Topic: Building a deb package
invalid URL:  https://raw.githubusercontent.com/Motion-Project/motion-packaging/master/buildplus.sh
doc page: URL: https://motion-project.github.io/motionplus_build.html

While trying to download the script,  terminal throwing error such as connection refused, Network is unreachable.  

![image](https://github.com/Motion-Project/Motion-Project.github.io/assets/11908787/817ef9f2-2b05-4e6a-834c-510c09504752)

**Comment by Mr-Dave** [comment]
If may be something with your network or github.  I just checked it and things downloaded fine.

**Comment by abdullahfarwees** [comment]
In India, Some of the network operator blocked the raw git content URL, Hence this issue raised. No changes required from the team side. Hence closing the ticket.
